<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ListCheckboxControls</name>
   <tag></tag>
   <elementGuidId>83da4510-c293-4fc5-a1db-7d372ec16f9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//md-checkbox[@ng-model=&quot;topping.wanted&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//md-checkbox[@ng-model=&quot;topping.wanted&quot;]</value>
   </webElementProperties>
</WebElementEntity>
