<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AutoCompleteDropdownFloatingLabel</name>
   <tag></tag>
   <elementGuidId>4489e35f-11e1-45a2-8031-eb9c34e6afd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//md-autocomplete[@input-aria-describedby=&quot;favoriteStateDescription&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//md-autocomplete[@input-aria-describedby=&quot;favoriteStateDescription&quot;]</value>
   </webElementProperties>
</WebElementEntity>
